name: 'Qt6 App Builder'
description: 'Build a Qt6 Application'
author: 'Tong Zhang'
inputs:
  project_file:
    description: 'Project file name'
    required: true
  app_name:
    description: 'Output app name'
    required: true
  exec_names:
    description: 'Executable names'
    required: true
  main_exec:
    description: 'Main executable name'
    required: false
    default: ''
  app_version:
    description: 'Version of app'
    required: false
    default: ''
  app_desc:
    description: 'Description of app'
    required: false
    default: ''
  dist_dir:
    description: 'Directory for built artifacts'
    required: false
    default: 'dist'
  qt_deployer_opts:
    description: 'Options for linuxdeployqt'
    required: false
    default: '-bundle-non-qt-libs -no-translations'
  makeself_opts:
    description: 'Options for makeself'
    required: false
    default: '--notemp --nox11 --tar-quietly --xz'

outputs:
  run_filename:
    description: 'The generated self-extract run file'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project_file }}
    - ${{ inputs.app_name }}
    - ${{ inputs.exec_names }}
    - ${{ inputs.main_exec }}
    - ${{ inputs.app_version }}
    - ${{ inputs.app_desc }}
    - ${{ inputs.dist_dir }}
    - ${{ inputs.qt_deployer_opts }}
    - ${{ inputs.makeself_opts }}
