name: 'Qt6 App Builder'
description: 'Build a Qt6 Application'
inputs:
  project_name:
    description: 'Project file name'
    required: true
  app_name:
    description: 'Output app name'
    required: true
  exec_names:
    description: 'Executable names'
    required: true
  dist_dir:
    description: 'Directory for built artifacts'
    required: true
    default: 'dist'
  qt_deployer_opts:
    description: 'Options for linuxdeployqt'
    required: true
    default: '-bundle-non-qt-libs -no-translations'

outputs:
  time: # id of output
    description: 'The time we greeted you'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project_name }}
    - ${{ inputs.app_name }}
    - ${{ inputs.exec_names }}
    - ${{ inputs.dist_dir }}
    - ${{ inputs.qt_deployer_opts }}
